### PR TITLE
Fix/seperate json attributes

### LINKED ISSUE #51: Use separate-json-attributes
Curious why not use `separate-json-attributes` for the EvtxParserSettings?

The issue with not using this settings is that it causes inconsistent json attribute naming standard:
image

When ever a XML element as an attribute, the JSON field will split into a `#text` and `#attributes`. This causes issues on many fronts. Using `separate-json-attributes` setting for the parser will normalize the fields and an XML element's value will always be the field name and any element attributes will be placed under `<ELEMENT_NAME>_attributes`. This prevents inconsistent field names in JSON serializations.

Some other references:
- https://youtu.be/9lu3NOaNXdY?t=591
- https://github.com/omerbenamram/evtx/issues/198

If you are open to this I can create a PR

### PR DESCRIPTION
**Pull request by fscc-jamesd**
This PR resolves #51

### CODE REVIEW

File: src/hunt/modules.rs [hunk 1]
```diff
@@ -538,7 +524,8 @@ pub fn detect_kaspersky_detections(
     let threat_name;
 
     // Kaspersky puts the relevant data in a Vec. Here we locate it and extract the key fields
-    if let Some(threat_data) = ajson::get(&event.to_string(), "Event.EventData.Data.#text") {
+    println!("event_data: {:?}", &event.to_string());
```
Comment (fscc-alexkornitzer) [inline src/hunt/modules.rs:527]: This needs deleting.

**Review by fscc-alexkornitzer — CHANGES_REQUESTED** [review]
All the commits need squashing too before this is merged IMO.

File: src/hunt/modules.rs (hunk 1 above)
Comment (fscc-jamesd) [reply src/hunt/modules.rs:527]: Ah hero, thanks for tthat spot. Will also squash

**Review by fscc-alexkornitzer — APPROVED** [review]
